
EXTRA_CFLAGS += -Iarch/arm/mach-msm
obj-$(CONFIG_MACH_MSM8225_C8680) += board-cellon-C8680-display.o
obj-$(CONFIG_MACH_MSM8225_C8680) += board-cellon-C8680-io.o


obj-$(CONFIG_MACH_MSM8225_C8680) += board-cellon-C8680-storage.o

ifdef CONFIG_ENABLE_CELLON_C8680_WLAN
obj-$(CONFIG_MACH_MSM8225_C8680) += board-cellon-C8680-wlan.o
endif
ifdef CONFIG_ENABLE_CELLON_C8680_BT
obj-$(CONFIG_MACH_MSM8225_C8680) += board-cellon-C8680-bt.o
endif
ifdef CONFIG_ENABLE_CELLON_C8680_SENSORS
obj-$(CONFIG_MACH_MSM8225_C8680) += board-cellon-C8680-sensor.o
endif
ifdef CONFIG_ENABLE_CELLON_C8680_CAMERA
obj-$(CONFIG_MACH_MSM8225_C8680) += board-cellon-C8680-camera.o
endif
obj-$(CONFIG_MACH_MSM8225_C8680) += board-cellon-C8680.o

#obj-$(CONFIG_MACH_MSM8225_C8680) += board-cellon-C8680-audio.o



obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681.o
obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681-regulator.o
obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681-display.o
obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681-io.o
obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681-bt.o
obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681-sensor.o
obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681-camera.o
obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681-wlan.o
obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681-storage.o
obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681-audio.o
obj-$(CONFIG_MACH_MSM8225_C8681) += board-cellon-C8681-camera.o
